[tool.poetry]
name = "learn-fasthtml"
version = "0.1.0"
description = ""
authors = ["Season <season.saw@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
python-fasthtml = "^0.6.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
